apiVersion: v1alpha1
kind: rule
meta:
  name: IsAgentsInstalledInVMs
  purpose: Is Agents Installed In VMs
  description: Is Agents Installed In VMs
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - azureappconnector
spec:
  inputs:
    VMsExtensionsDataFilePath: <<MINIO_FILE_PATH>>
    ControlConfigFilePath: <<MINIO_FILE_PATH>>
    ControlName:
  inputsMeta__:
  - name: VMsExtensionsDataFilePath
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: ControlConfigFilePath
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: ControlName
    dataType: STRING
    repeated: false
    defaultValue: ''
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: IsAgentInstalledInVMs  
    alias: t1
    type: task
    appTags:
      appType:
      - azureappconnector
      environment:
      - logical
      execlevel:
      - app
    purpose: IsAgentInstalledInVMs 
    description: IsAgentInstalledInVMs
  ioMap:
  - 't1.Input.VMsExtensionsDataFilePath:=*.Input.VMsExtensionsDataFilePath'
  - 't1.Input.ControlConfigFilePath:=*.Input.ControlConfigFilePath'
  - 't1.Input.ControlName:=*.Input.ControlName'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.AgentInstalledInVMs:=t1.Output.AgentInstalledInVMs'
  - '*.Output.LogFile:=t1.Output.LogFile'
