authors:
- sangavi.l@continube.com
domain: continube
createdDate: 11/12/2023
name: AWSRootAccountAccessKeyReport
displayName: AWS Root Account Access Key Report
version: '1.0'
description: Generate a compliance report of AWS root account access key report
shaToken: ''
showInCatalog: true
icon: fas fa-sort-amount-down-alt
type: go
tags:
- application
applicationType: application
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: AWSCredentialReport
  description: AWS Credential Report
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: ''
  showField: true
  required: true
outputs:
- name: NoAccessKeyWithRootAccount
  description: No Access Key With Root Account
  dataType: FILE
- name: LogFile
  description: Log File
  dataType: FILE
- name: RootAccountAccessKeyFieldMeta
  description: Root Account Access Key Field Meta
  dataType: FILE
- name: CompliancePCT_
  description: Compliance Percentage
  dataType: INT
- name: ComplianceStatus_
  description: Compliance Status
  dataType: STRING
