authors:
- lokesh.b@continube.com
domain: continube
createdDate: 27/12/2023
name: GetAzureLogAnalyticsWorkSpaceDetails
displayName: Get Azure Log Analytics WorkSpace Details
version: '1.0'
description: Get Azure Log Analytics WorkSpace Details
shaToken: ''
showInCatalog: true
icon: fas fa-sort-amount-down-alt
type: python
tags:
- application
applicationType: application
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
outputs:
- name: AzureLogAnalyticsWorkSpaceDetails
  description: Azure Log Analytics WorkSpace Details
  dataType: FILE
- name: LogFile
  description: LogFile
  dataType: FILE
- name: CompliancePCT_
  description: Compliance Percentage
  dataType: INT
- name: ComplianceStatus_
  description: Compliance Status
  dataType: STRING
