apiVersion: v1alpha1
kind: rule
meta:
  name: IsDiagnosticLogsEnabledInAzureServiceBus
  purpose: Is Diagnostic Logs Enabled In Azure ServiceBus
  description: Is Diagnostic Logs Enabled In Azure ServiceBus
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - azureappconnector
spec:
  inputs:
    ServiceBusDiagnosticSettingsDataFilePath: <<MINIO_FILE_PATH>>
  inputsMeta__:
  - name: ServiceBusDiagnosticSettingsDataFilePath
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: IsDiagnosticLogsEnabledInServiceBus
    alias: t1
    type: task
    appTags:
      appType:
      - azureappconnector
      environment:
      - logical
      execlevel:
      - app
    purpose: IsDiagnosticLogsEnabledInServiceBus
    description: IsDiagnosticLogsEnabledInServiceBus
  ioMap:
  - 't1.Input.ServiceBusDiagnosticSettingsDataFilePath:=*.Input.ServiceBusDiagnosticSettingsDataFilePath'
  - '*.Output.DiagnosticLogsInServiceBusNameSpace:=t1.Output.DiagnosticLogsInServiceBusNameSpace'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
