apiVersion: v1alpha1
kind: rule
meta:
  name: AzurePolicyRunResult
  purpose: Azure Policy Run Result
  description: Azure Policy Run Result
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - azureappconnector
spec:
  tasks:
  - name: GetAzurePolicyRunResult
    alias: t1
    type: task
    appTags:
      appType:
      - azureappconnector
      environment:
      - logical
      execlevel:
      - app
    purpose: GetAzurePolicyRunResult
    description: GetAzurePolicyRunResult

  ioMap:
  - '*.Output.AzurePolicyRunResult:=t1.Output.AzurePolicyRunResult'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.LogFile:=t1.Output.LogFile'
