userObject:
  app:
    name: AWSAppConnector
    appURL: https://aws.amazon.com
    appPort: "0"
    appTags:
      appType:
      - aws
      environment:
      - logical
      execlevel:
      - app
    userDefinedCredentials:
      AWSIAM:
        AccessKey: "$AWS_ACCESS_KEY"
        SecretKey: "$AWS_SECRET_KEY"
      AWSRole:
        AccessKey: "$AWS_ACCESS_KEY"
        SecretKey: "$AWS_SECRET_KEY"
        RoleARN: "$AWS_ROLE_ARN"
userInputs:
  SecurityHubFindingsFile: <<MINIO_FILE_PATH>>
  ControlName: # To identify the ControlName, please refer to the 'ControlName' field in the '/catalog/globalcatalog/rules/ProcessFindingsFromSecurityHub/ControlConfig.json' file.
  ControlConfigFile: <<MINIO_FILE_PATH>>
fromDate: "2023-11-10T06:07:54Z"
toDate: "2023-11-10T06:07:54Z"
