authors:
- lokesh.b@continube.com
domain: continube
createdDate: 14/12/2023
name: StandardizeAzureDefenderReportTask
displayName: StandardizeAzureDefenderReportTask
version: '1.0'
description: StandardizeAzureDefenderReportTask
shaToken: ''
showInCatalog: true
icon: fa-solid fa-database
type: python
tags:
- application
applicationType: application
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: RuleDisplayName
  description: RuleDisplayName
  dataType: STRING
  repeated: false
  allowedValues: []
  defaultValue: ''
  showField: true
  required: true
- name: RuleConfig
  description: RuleConfig
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: ''
  showField: true
  required: true
- name: AzureReportData
  description: AzureReportData
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: ''
  showField: true
  required: true
outputs:
- name: CompliancePCT_
  description: Compliance Percentage
  dataType: INT
- name: ComplianceStatus_
  description: Compliance Status
  dataType: STRING
- name: AzureDefenderReport
  description: AzureDefenderReport
  dataType: FILE
- name: LogFile
  description: LogFile
  dataType: FILE
