apiVersion: v1alpha1
kind: rule
meta:
  name: StandardizeAzureDefenderReport
  purpose: Standardize Azure Defender Report
  description: Standardize Azure Defender Report
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - azureappconnector
spec:
  inputs:
    RuleDisplayName:
    RuleConfig: <<MINIO_FILE_PATH>>
    AzureReportData: <<MINIO_FILE_PATH>>
  inputsMeta__:
  - name: RuleDisplayName
    dataType: STRING
    repeated: false
    defaultValue: ''
    allowedValues: []
    showField: true
    required: true
  - name: RuleConfig
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: AzureReportData
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: StandardizeAzureDefenderReportTask
    alias: t1
    type: task
    appTags:
      appType:
      - azureappconnector
      environment:
      - logical
      execlevel:
      - app
    purpose: StandardizeAzureDefenderReportTask
    description: StandardizeAzureDefenderReportTask
  ioMap:
  - 't1.Input.RuleDisplayName:=*.Input.RuleDisplayName'
  - 't1.Input.RuleConfig:=*.Input.RuleConfig'
  - 't1.Input.AzureReportData:=*.Input.AzureReportData'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.AzureDefenderReport:=t1.Output.AzureDefenderReport'
  - '*.Output.LogFile:=t1.Output.LogFile'
