id: ""
apiVersion: v1alpha1
kind: applicationClass
meta:
  name: Kubernetes
  displayName: Kubernetes
  shortDescription: ""
  longDescription: ""
  labels:
    appType:
    - kubernetes
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - kubernetes
spec:
  url: http://localhost.com
  ipv4Address: ""
  ipv6Address: ""
  port: 0
  validation:
    taskName: ValidateKubernetes
    taskVersion: ""
  credentialTypes:
  - name: Jumphost
    version: 1.1.1
    repeated: false
  selectors: null
  defaultCredentialType:
    name: Jumphost
    version: 1.1.1
  applicationType: ""
  directAccess: true
  linkableApplicationClasses:
  - name: AWSAppConnector
  - name: ServiceNowConnector
  - name: ArgoCDConnector
  management: false
  allowableChildrenApplicationClasses: []
  type: user
  expectedSystemApplicationClasses: []
isVersionToBeOverride: true
