authors:
- mani.m@continube.com
domain: continube
createdDate: 11/12/2023
name: AWSMFAReport
displayName: AWS MFA Report
version: '1.0'
description: Aws users MFA details in standard format
shaToken: ''
showInCatalog: true
icon: fas fa-sort-amount-down-alt
type: go
tags:
- application
applicationType: application
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: AWSCredentialReport
  description: AWS Credential Report
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: <<MINIO_FILE_PATH>>
  showField: true
  required: true
outputs:
- name: AWSMFAReport
  description: AWS MFA Report
  dataType: FILE
- name: LogFile
  description: LogFile
  dataType: FILE
- name: MetaFile
  description: Meta File
  dataType: FILE
- name: CompliancePCT_
  description: Compliance Percentage
  dataType: INT
- name: ComplianceStatus_
  description: Compliance Status
  dataType: STRING
