apiVersion: v1alpha1
kind: rule
meta:
  name: AzureMFAEnabledForADUsers
  purpose: Azure MFA Enabled For ADUsers
  description: Azure MFA Enabled For ADUsers
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - azureappconnector
spec:
  inputs:
    AzureADUsersAuthDataPath: <<MINIO_FILE_PATH>>
  inputsMeta__:
  - name: AzureADUsersAuthDataPath
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: AzureADMFAEnabled
    alias: t1
    type: task
    appTags:
      appType:
      - azureappconnector
      environment:
      - logical
      execlevel:
      - app
    purpose: AzureADMFAEnabled
    description: AzureADMFAEnabled
  ioMap:
  - 't1.Input.AzureADUsersAuthDataPath:=*.Input.AzureADUsersAuthDataPath'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.AzureADMFAEnabled:=t1.Output.AzureADMFAEnabled'
  - '*.Output.LogFile:=t1.Output.LogFile'
