apiVersion: v1alpha1
kind: rule
meta:
  name: GetAWSConfigRuleEvaluationDetails
  purpose: Get AwsConfig rule evaluation details 
  description: Get AwsConfig rule evaluation details 
  labels:
    appType:
    - aws
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - aws
spec:
  inputs:
    Region: 
  inputsMeta__:
  - name: Region
    dataType: STRING
    repeated: true
    defaultValue: ''
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: GetAWSConfigRuleEvaluationDetails
    alias: t1
    type: task
    appTags:
      appType:
      - aws
      environment:
      - logical
      execlevel:
      - app
    purpose: Get AwsConfig rule evaluation details 
    description: Get AwsConfig rule evaluation details 
  ioMap:
  - 't1.Input.Region:=*.Input.Region'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.AWSConfigRulesJSON:=t1.Output.AWSConfigRulesJSON'
  - '*.Output.AWSConfigRuleEvaluationStatusJSON:=t1.Output.AWSConfigRuleEvaluationStatusJSON' 
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.MetaDataFile:=t1.Output.MetaDataFile'