authors:
- lokesh.b@continube.com
domain: continube
createdDate: 27/12/2023
name: FetchAzureServicePrincipals
displayName: Fetch Azure Service Principals
version: '1.0'
description: Fetch Azure Service Principals
shaToken: ''
showInCatalog: true
icon: fas fa-sort-amount-down-alt
type: python
tags:
- application
applicationType: application
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
outputs:
- name: AzureServicePrincipalsData
  description: Azure Service Principals Data
  dataType: FILE
- name: LogFile
  description: LogFile
  dataType: FILE
- name: CompliancePCT_
  description: Compliance Percentage
  dataType: INT
- name: ComplianceStatus_
  description: Compliance Status
  dataType: STRING
