apiVersion: v1alpha1
kind: rule
meta:
  name: ProcessFindingsFromSecurityHub
  purpose: Process Findings From AWS SecurityHub
  description: Process Findings From AWS SecurityHub
  labels:
    appType:
    - aws
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - aws
spec:
  inputs:
    SecurityHubFindingsFile: <<MINIO_FILE_PATH>>
    ControlName: 
    ControlConfigFile: <<MINIO_FILE_PATH>>
  inputsMeta__:
  - name: SecurityHubFindingsFile
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: ControlName
    dataType: STRING
    repeated: false
    defaultValue: ''
    allowedValues: []
    showField: true
    required: true
  - name: ControlConfigFile
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: ProcessSecurityHubFindings
    alias: t1
    type: task
    appTags:
      appType:
      - aws
      environment:
      - logical
      execlevel:
      - app
    purpose: Process SecurityHub Findings
    description: Process SecurityHub Findings
  ioMap:  
  - 't1.Input.SecurityHubFindingsFile:=*.Input.SecurityHubFindingsFile'
  - 't1.Input.ControlName:=*.Input.ControlName'
  - 't1.Input.ControlConfigFile:=*.Input.ControlConfigFile'
  - '*.Output.SecurityHubReport:=t1.Output.SecurityHubReport' 
  - '*.Output.SecurityHubFieldMeta:=t1.Output.SecurityHubFieldMeta'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'