authors:
- musadhiek.p@continube.com
domain: continube
createdDate: 14/12/2023
name: IsAgentInstalledInVMs
displayName: Is Agent Installed In Vritual Machines
version: '1.0'
description: Is Agent Installed In Vritual Machines
shaToken: ''
showInCatalog: true
icon: fa-solid fa-database
type: python
tags:
- application
applicationType: application
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: VMsExtensionsDataFilePath
  description: VMsExtensionsDataFilePath
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: ''
  showField: true
  required: true
- name: ControlConfigFilePath
  description: ControlConfigFilePath
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: ''
  showField: true
  required: true
- name: ControlName
  description: ControlName
  dataType: STRING
  repeated: false
  allowedValues: []
  defaultValue: ''
  showField: true
  required: true
outputs:
- name: CompliancePCT_
  description: Compliance Percentage
  dataType: INT
- name: ComplianceStatus_
  description: Compliance Status
  dataType: STRING
- name: AgentInstalledInVMs
  description: AgentInstalledInVMs
  dataType: FILE
- name: LogFile
  description: LogFile
  dataType: FILE
