authors:
- musadhiek.p@continube.com
domain: continube
createdDate: 12/12/2023
name: AzureADMFAEnabled
displayName: Azure AD MFA Enabled
version: '1.0'
description: Azure AD MFA Enabled
shaToken: ''
showInCatalog: true
icon: fa-solid fa-database
type: python
tags:
- application
applicationType: application
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: AzureADUsersAuthDataPath
  description: AzureADUsersAuthDataPath
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: ''
  showField: true
  required: true
outputs:
- name: AzureADMFAEnabled
  description: AzureADMFAEnabled
  dataType: FILE
- name: LogFile
  description: LogFile
  dataType: FILE
- name: ComplianceStatus_
  description: ComplianceStatus_
  dataType: STRING
- name: CompliancePCT_
  description: CompliancePCT_
  dataType: INT
