authors:
- musadhiek.p@continube.com
domain: continube
createdDate: 12/12/2023
name: AzurePolicyFilterAndFormatRunResult
displayName: Azure Policy Filter And Format Run Result
version: '1.0'
description: Azure Policy Filter And Format Run Result
shaToken: ''
showInCatalog: true
icon: fa-solid fa-database
type: python
tags:
- application
applicationType: application
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: ControlConfigFilePath
  description: ControlConfigFilePath
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: ''
  showField: true
  required: true
- name: AzurePolicyRunResultFilePath
  description: AzurePolicyRunResultFilePath
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: ''
  showField: true
  required: true
- name: ControlName
  description: ControlName
  dataType: STRING
  repeated: false
  allowedValues: []
  defaultValue: ''
  showField: true
  required: true
outputs:
- name: FilteredAndFormattedControlEvidence
  description: FilteredAndFormattedControlEvidence
  dataType: FILE
- name: LogFile
  description: LogFile
  dataType: FILE
- name: ComplianceStatus_
  description: ComplianceStatus_
  dataType: STRING
- name: CompliancePCT_
  description: CompliancePCT_
  dataType: INT
