authors:
- lokesh.b@continube.com
domain: continube
createdDate: 17/04/2024
name: AzureLogAnalyticsWkSpaceRetentionPeriodReport
displayName: Azure Log Analytics WorkSpace Retention Period Report
version: '1.0'
description: Azure Log Analytics WorkSpace Retention Period Report
shaToken: ''
showInCatalog: true
icon: fa-solid fa-database
type: python
tags:
- generic
applicationType: generic
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: AzureLogAnalyticsWorkSpaceData # A unique identifier of the task input
  description: AzureLogAnalyticsWorkSpaceData  # A concise description of the task input
  dataType: FILE
  repeated: false
  allowedValues: [] # Optional. Specifies allowed values for the input. Use a comma-separated list for multiple values.
  defaultValue:  # optional. You can specify the default value (either a string or a number) at this point, for now, it supports a single value.
  showField: true  # boolean: true | false
  required: true
- name: RetentionInDays # A unique identifier of the task input
  description: RetentionInDays  # A concise description of the task input
  dataType: INT
  repeated: false
  allowedValues: [] # Optional. Specifies allowed values for the input. Use a comma-separated list for multiple values.
  defaultValue:  # optional. You can specify the default value (either a string or a number) at this point, for now, it supports a single value.
  showField: true  # boolean: true | false
  required: true
outputs:
- name: LogAnalyticsWkSpaceRetentionPeriodReport
  description: Log Analytics Work Space Retention Period Report
  dataType: FILE
- name: LogFile
  description: LogFile
  dataType: FILE
- name: ComplianceStatus_
  description: compliance status of the task
  dataType: STRING
- name: CompliancePCT_
  description: compliance percentage of the task
  dataType: INT
