authors:
- sangavi.l@continube.com
domain: continube
createdDate: 01/03/2024
name: CheckAWSDBInstanceBackup
displayName: Checks if RDS DB instances have backups enabled
version: '1.0'
description: Check AWS DB Instance Backup
shaToken: ''
showInCatalog: true
icon: fas fa-sort-amount-down-alt
type: python
tags:
- application
applicationType: application
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: MinimumRequiredRetentionPeriod
  description: MinimumRequiredRetentionPeriod
  dataType: INT
  repeated: false
  allowedValues: []
  defaultValue: ''
  showField: true
  required: true
- name: RDSDBInstancesList
  description: RDSDBInstancesList
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: <<MINIO_FILE_PATH>>
  showField: true
  required: true
- name: LogFile
  description: LogFile
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: <<MINIO_FILE_PATH>>
  showField: true
  required: true
outputs:
- name: DBInstanceBackupEnabled
  description: DB Instance Backup Enabled
  dataType: FILE
- name: LogFile
  description: LogFile
  dataType: FILE
- name: ComplianceStatus_
  description: ComplianceStatus_
  dataType: STRING
- name: CompliancePCT_
  description: CompliancePCT_
  dataType: INT
