apiVersion: v1alpha1
kind: rule
meta:
  name: AWSMFAPolicySimulatorReport
  purpose: Check if given service:action definitions and conditions are implemented in the policy
  description: Check if given service:action definitions and conditions are implemented in the policy
  icon: <svg width='50px' height='50px' viewBox='-117 0 490 490' version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' preserveAspectRatio='xMidYMid'><g><path d='M21,165.75 L0,172.606 L21.75,175.125 L21,165.75' fill='#3C4929'>  </path>         <path d='M19.955,206.806 L128,213.714 L236.045,206.806 L128,185.75 L19.955,206.806' fill='#3C4929'></path><path d='M234.5,175.125 L256,172.606 L234.5,166.875 L234.5,175.125' fill='#3C4929'>  </path>         <path d='M157.387,352.929 L213.993,366.325 L157.237,383.441 L157.387,352.929' fill='#B7CA9D'>  </path>         <path d='M19.955,92.221 L19.955,54.019 L128,0 L128.482,0.405 L128.234,48.901 L128,49.003 L127.595,50.12 L68.497,73.976 L67.955,158.013 L99.407,152.723 L128,147.002 L128,490.03 L95.631,473.853 L95.631,428.082 L67.277,416.744 L67.277,202.069 L19.955,206.806 L19.955,168.611 L0,172.606 L0,100.198 L19.955,92.221' fill='#4B612C'>  </path>         <path d='M99.408,152.727 L67.277,159.151 L67.277,73.28 L99.408,83.298 L99.408,152.727' fill='#759C3E'>  </path>         <path d='M183.925,27.959 L236.031,54.019 L236.031,92.221 L256,100.198 L256,172.6 L236.031,168.611 L236.031,206.806 L210.59,204.268 L188.709,202.069 L188.709,245.008 L236.045,245.008 L236.045,284.292 L214.048,286.266 L214.048,325.877 L160.356,336.549 L160.356,382.319 L213.926,366.42 L214.048,406.8 L160.356,428.082 L160.356,473.853 L128,490.03 L128,147.002 L156.572,152.712 L187.155,156.75 L187.155,73.966 L128.817,51.468 L128,49.003 L128,0 L183.925,27.959' fill='#759C3E'></path><path d='M160.356,61.941 L128,49.01 L67.277,73.28 L99.408,83.298 L160.356,61.941' fill='#3C4929'></path><path d='M67.277,73.28 L128,49.01 L140.775,54.114 L160.356,61.941 L188.709,73.294 L187.194,74.835 L158.318,83.826 L156.578,83.298 L128,73.28 L99.408,83.298 L67.277,73.28' fill='#3C4929'>  </path>         <path d='M156.578,83.298 L188.709,73.294 L188.709,159.158 L156.578,152.712 L156.578,83.298' fill='#4B612C'></path></g></svg>
  labels:
    appType:
    - aws
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - aws
spec:
  inputs:
    Users: ''
    UserStatus: ''
    Groups: ''
    GroupStatus: ''
    Roles: ''
    RoleStatus: ''
    MFARecommendationFile: <<MINIO_FILE_PATH>>
    AccountAuthorizationDetails: <<MINIO_FILE_PATH>>
  inputsMeta__:
  - name: Users
    dataType: STRING
    repeated: false
    defaultValue: ''
    allowedValues: []
    showField: true
    required: true
  - name: UserStatus
    dataType: STRING
    repeated: false
    defaultValue: ''
    allowedValues: []
    showField: true
    required: true
  - name: Groups
    dataType: STRING
    repeated: false
    defaultValue: ''
    allowedValues: []
    showField: true
    required: true
  - name: GroupStatus
    dataType: STRING
    repeated: false
    defaultValue: ''
    allowedValues: []
    showField: true
    required: true
  - name: Roles
    dataType: STRING
    repeated: false
    defaultValue: ''
    allowedValues: []
    showField: true
    required: true
  - name: RoleStatus
    dataType: STRING
    repeated: false
    defaultValue: ''
    allowedValues: []
    showField: true
    required: true
  - name: MFARecommendationFile
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: AccountAuthorizationDetails
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: AWSMFAPolicySimulatorReport
    alias: t1
    type: task
    appTags:
      appType:
      - aws
      environment:
      - logical
      execlevel:
      - app
    purpose: Check if given service:action definitions and conditions are implemented in the policy
    description: Check if given service:action definitions and conditions are implemented in the policy
  ioMap:
  - t1.Input.Users:=*.Input.Users
  - t1.Input.UserStatus:=*.Input.UserStatus
  - t1.Input.Groups:=*.Input.Groups
  - t1.Input.GroupStatus:=*.Input.GroupStatus
  - t1.Input.Roles:=*.Input.Roles
  - t1.Input.RoleStatus:=*.Input.RoleStatus
  - t1.Input.MFARecommendationFile:=*.Input.MFARecommendationFile
  - t1.Input.AccountAuthorizationDetails:=*.Input.AccountAuthorizationDetails
  - '*.Output.MFAPolicySimulatorReport:=t1.Output.MFAPolicySimulatorReport'
  - '*.Output.LogFile:=t1.Output.LogFile'
  - '*.Output.MetaFile:=t1.Output.MetaFile'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
