authors:
- musadhiek.p@continube.com
domain: continube
createdDate: 04/02/2024
name: CheckHeaders
displayName: Check Headers
version: '1.0'
description: Check Headers
shaToken: ''
showInCatalog: true
icon: fa-solid fa-database
type: go
tags:
- generic
applicationType: generic
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: HarFile # A unique identifier of the task input
  description: HarFile # A concise description of the task input
  dataType: FILE # data type of the input. Available Types STRING, INT, FLOAT, FILE
  repeated: false
  allowedValues: [] # Optional. Specifies allowed values for the input. Use a comma-separated list for multiple values.
  defaultValue:  # optional. You can specify the default value (either a string or a number) at this point, for now, it supports a single value.
  showField: true  # boolean: true | false
  isRequired: true # boolean: true | false
outputs:
- name: StrictTransportSecurityLog
  description: StrictTransportSecurityLog
  dataType: FILE 
- name: StdStrictTransportSecurityLog
  description: StdStrictTransportSecurityLog
  dataType: FILE 
- name: PublicKeyPinsLog
  description: PublicKeyPinsLog
  dataType: FILE 
- name: StdPublicKeyPinsLog
  description: StdPublicKeyPinsLog
  dataType: FILE 
- name: ExpectCTLog
  description: ExpectCTLog
  dataType: FILE 
- name: StdExpectCTLog
  description: StdExpectCTLog
  dataType: FILE 
- name: XFrameOptionsLog
  description: XFrameOptionsLog
  dataType: FILE 
- name: StdXFrameOptionsLog
  description: StdXFrameOptionsLog
  dataType: FILE 
- name: AccessControlAllowOriginLog
  description: AccessControlAllowOriginLog
  dataType: FILE 
- name: StdAccessControlAllowOriginLog
  description: StdAccessControlAllowOriginLog
  dataType: FILE 
- name: XContentTypeOptionsLog
  description: XContentTypeOptionsLog
  dataType: FILE 
- name: StdXContentTypeOptionsLog
  description: StdXContentTypeOptionsLog
  dataType: FILE 
- name: RefererPolicyLog
  description: RefererPolicyLog
  dataType: FILE 
- name: StdRefererPolicyLog
  description: StdRefererPolicyLog
  dataType: FILE 
- name: ETagLog
  description: ETagLog
  dataType: FILE 
- name: StdETagLog
  description: StdETagLog
  dataType: FILE 
- name: ErrorDetails
  description: ErrorDetails
  dataType: string
- name: LogFile
  description: LogFile
  dataType: FILE     
- name: ComplianceStatus_
  description: compliance status of the task
  dataType: STRING
- name: CompliancePCT_
  description: compliance percentage of the task
  dataType: INT
