userObject:
  app:
    name: AWSAppConnector
    appURL: https://aws.amazon.com
    appPort: "0"
    appTags:
      appType:
      - aws
      environment:
      - logical
      execlevel:
      - app
    userDefinedCredentials:
      AWSRole:
        AccessKey: "$AWS_ACCESS_KEY"
        SecretKey: "$AWS_SECRET_KEY"
        RoleARN: "$AWS_ROLE_ARN"
      AWSIAM:
        AccessKey: "$AWS_ACCESS_KEY"
        SecretKey: "$AWS_SECRET_KEY"
userInputs:
  AWSConfigRule: # To identify the AWSConfigRule, please refer to the 'RuleName' field in the '/catalog/globalcatalog/rules/GetFilterAWSConfigRuleEvaualtionDetails/RuleConfig.json' file.
  AWSConfigRulesFile: <<MINIO_FILE_PATH>>
  AWSConfigRuleEvaluationStatusFile: <<MINIO_FILE_PATH>>
  RuleConfigFile: <<MINIO_FILE_PATH>>
fromDate: "2023-12-10T06:07:54Z"
toDate: "2023-12-10T06:07:54Z"