apiVersion: v1alpha1
kind: rule
meta:
  name: AzureLogAnalyticsWorkSpaceDetails
  purpose: Azure Log Analytics Work Space Details
  description: Azure Log Analytics Work Space Details
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - azureappconnector
spec:
  tasks:
  - name: GetAzureLogAnalyticsWorkSpaceDetails
    alias: t1
    type: task
    appTags:
      appType:
      - azureappconnector
      environment:
      - logical
      execlevel:
      - app
    purpose: GetAzureLogAnalyticsWorkSpaceDetails
    description: GetAzureLogAnalyticsWorkSpaceDetails
  ioMap:
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.AzureLogAnalyticsWorkSpaceDetails:=t1.Output.AzureLogAnalyticsWorkSpaceDetails'
  - '*.Output.LogFile:=t1.Output.LogFile'
