apiVersion: v1alpha1
kind: rule
meta:
  name: GenerateAzureBackupStorageAccessUsersList
  purpose: Generate Azure Backup Storage Access Users List
  description: Generate Azure Backup Storage Access Users List
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - azureappconnector
spec:
  inputs:
    BackupStorageRegexPattern:
  inputsMeta__:
  - name: BackupStorageRegexPattern
    dataType: STRING
    repeated: false
    defaultValue: backup
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: GetAzureStorageAccountsData
    alias: t1
    type: task
    appTags:
      appType:
      - azureappconnector
      environment:
      - logical
      execlevel:
      - app
    purpose: GetAzureStorageAccountsData
    description: GetAzureStorageAccountsData
  - name: FetchAzureRoleDefinitionsDetails
    alias: t2
    type: task
    appTags:
      appType:
      - azureappconnector
      environment:
      - logical
      execlevel:
      - app
    purpose: FetchAzureRoleDefinitionsDetails
    description: FetchAzureRoleDefinitionsDetails
  - name: FetchAzureUsers
    alias: t3
    type: task
    appTags:
      appType:
      - azureappconnector
      environment:
      - logical
      execlevel:
      - app
    purpose: FetchAzureUsers
    description: FetchAzureUsers
  - name: FetchAzureGroups
    alias: t4
    type: task
    appTags:
      appType:
      - azureappconnector
      environment:
      - logical
      execlevel:
      - app
    purpose: FetchAzureGroups
    description: FetchAzureGroups
  - name: FetchAzureServicePrincipals
    alias: t5
    type: task
    appTags:
      appType:
      - azureappconnector
      environment:
      - logical
      execlevel:
      - app
    purpose: FetchAzureServicePrincipals
    description: FetchAzureServicePrincipals
  - name: FetchAzureRoleAssignmentsData
    alias: t6
    type: task
    appTags:
      appType:
      - azureappconnector
      environment:
      - logical
      execlevel:
      - app
    purpose: FetchAzureRoleAssignmentsData
    description: FetchAzureRoleAssignmentsData
  - name: FetchAzureBackupStorageAccessUsersList
    alias: t7
    type: task
    appTags:
      appType:
      - azureappconnector
      environment:
      - logical
      execlevel:
      - app
    purpose: FetchAzureBackupStorageAccessUsersList
    description: FetchAzureBackupStorageAccessUsersList
  ioMap:
  - 't6.Input.AzureRoleDefinitionsData:=t2.Output.AzureRoleDefinitionsData'
  - 't6.Input.AzureUsersList:=t3.Output.AzureUsersList'
  - 't6.Input.AzureGroupsList:=t4.Output.AzureGroupsList'
  - 't6.Input.AzureServicePrincipalsData:=t5.Output.AzureServicePrincipalsData'
  - 't7.Input.AzureRoleAssignmentsData:=t6.Output.AzureRoleAssignmentsData'
  - 't7.Input.AzureUsersList:=t3.Output.AzureUsersList'
  - 't7.Input.AzureStorageAccountsData:=t1.Output.AzureStorageAccountsData'
  - 't7.Input.BackupStorageRegexPattern:=*.Input.BackupStorageRegexPattern'
  - '*.Output.CompliancePCT_:=t7.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t7.Output.ComplianceStatus_'
  - '*.Output.AzureBackupStorageAccessUsersList:=t7.Output.AzureBackupStorageAccessUsersList'
  - '*.Output.LogFile:=t7.Output.LogFile'
