authors:
- lokesh.b@continube.com
domain: continube
createdDate: 29/04/2024
name: EvaluateOpaAgainstCollectedManifestData
displayName: Evaluate Opa Against Collected Manifest Data
version: '1.0'
description: Evaluate Opa Against Collected Manifest Data
shaToken: ''
showInCatalog: true
icon: fa-solid fa-suitcase
type: go
tags:
- application
applicationType: generic
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: RegoFile
  description: RegoFile
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: <<MINIO_FILE_PATH>>
  showField: true
  required: true
- name: OpaConfigurationFile
  description: OpaConfigurationFile
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: <<MINIO_FILE_PATH>>
  showField: true
  required: true
- name: AuditFile
  description: AuditFile
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: <<MINIO_FILE_PATH>>
  showField: true
  required: true
- name: DataFile
  description: DataFile
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: <<MINIO_FILE_PATH>>
  showField: true
  required: true
- name: Query
  description: Query
  dataType: STRING
  repeated: false
  allowedValues: []
  defaultValue: ""
  showField: true
  required: true
outputs:
- name: OpaPolicyReport
  description: Opa Policy Report
  dataType: FILE
- name: AuditFile
  description: Audit File
  dataType: FILE
- name: ComplianceStatus_
  description: compliance status of the task
  dataType: STRING
- name: CompliancePCT_
  description: compliance percentage of the task
  dataType: INT
