apiVersion: v1alpha1
kind: rule
meta:
  name: MicrosoftDefender
  purpose: Microsoft Defender
  description: Microsoft Defender
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - azureappconnector
spec:
  tasks:
  - name: SecurityAssessment
    alias: t1
    type: task
    appTags:
      appType:
      - azureappconnector
      environment:
      - logical
      execlevel:
      - app
    purpose: SecurityAssessment
    description: SecurityAssessment
  ioMap:
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.AzureReport:=t1.Output.AzureReport'
  - '*.Output.LogFile:=t1.Output.LogFile'
