authors:
- lokesh.b@continube.com
domain: continube
createdDate: 27/12/2023
name: FetchAzureRoleAssignmentsData
displayName: Fetch Azure Role Assignments Data
version: '1.0'
description: Fetch Azure Role Assignments Data
shaToken: ''
showInCatalog: true
icon: fas fa-sort-amount-down-alt
type: python
tags:
- application
applicationType: application
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: AzureRoleDefinitionsData
  description: AzureRoleDefinitionsData
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: ''
  showField: true
  required: true
- name: AzureUsersList
  description: AzureUsersList
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: ''
  showField: true
  required: true
- name: AzureGroupsList
  description: AzureGroupsList
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: ''
  showField: true
  required: true
- name: AzureServicePrincipalsData
  description: AzureServicePrincipalsData
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: ''
  showField: true
  required: true
outputs:
- name: AzureRoleAssignmentsData
  description: Azure Role Assignments Data
  dataType: FILE
- name: LogFile
  description: LogFile
  dataType: FILE
- name: CompliancePCT_
  description: Compliance Percentage
  dataType: INT
- name: ComplianceStatus_
  description: Compliance Status
  dataType: STRING
