apiVersion: v1alpha1
kind: rule
meta:
  name: AzurePolicyFilteredAndFormattedControlEvidence
  purpose: Azure Policy Filtered And Formatted Control Evidence
  description: Azure Policy Filtered And Formatted Control Evidence
  labels:
    appType:
    - azureappconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - azureappconnector
spec:
  inputs:
    ControlName: ""
    ControlConfigFilePath: <<MINIO_FILE_PATH>>
    AzurePolicyRunResultFilePath: <<MINIO_FILE_PATH>>
  inputsMeta__:
  - name: ControlName
    dataType: STRING
    repeated: false
    defaultValue: ''
    allowedValues: []
    showField: true
    required: true
  - name: ControlConfigFilePath
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: AzurePolicyRunResultFilePath
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: AzurePolicyFilterAndFormatRunResult
    alias: t1
    type: task
    appTags:
      appType:
      - azureappconnector
      environment:
      - logical
      execlevel:
      - app
    purpose: Filter And Format AzurePolicyRunResult
    description: Filter And Format AzurePolicyRunResult
  ioMap:
  - 't1.Input.ControlName:=*.Input.ControlName'
  - 't1.Input.ControlConfigFilePath:=*.Input.ControlConfigFilePath'
  - 't1.Input.AzurePolicyRunResultFilePath:=*.Input.AzurePolicyRunResultFilePath'
  - '*.Output.FilteredAndFormattedControlEvidence:=t1.Output.FilteredAndFormattedControlEvidence'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.LogFile:=t1.Output.LogFile'
