userObject:
  app:
    name: AWSAppConnector
    appURL: https://aws.amazon.com
    appPort: "0"
    appTags:
      appType:
      - aws
      environment:
      - logical
      execlevel:
      - app
    userDefinedCredentials:
      AWSRole:
        AccessKey: "$AWS_ROLE_ACCESS_KEY"
        SecretKey: "$AWS_ROLE_SECRET_KEY"
        RoleARN: "$AWS_ROLE_ARN"
      AWSIAM:
        AccessKey: "$AWS_ACCESS_KEY"
        SecretKey: "$AWS_SECRET_KEY"
userInputs:
  Region: []
fromDate: "2024-02-29T06:07:54Z"
toDate: "2024-02-29T06:07:54Z"
