authors:
- vivek.p@continube.com
domain: continube
createdDate: 01/02/2024
name: HARCookieAnalyzer
displayName: HARCookieAnalyzer
version: '1.0'
description: HARCookieAnalyzer
shaToken: ''
showInCatalog: true
icon: fa-solid fa-database
type: python
tags:
- generic
applicationType: generic
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: CookieDBFile # A unique identifier of the task input
  description: CookieDBFile # A concise description of the task input
  dataType: FILE
  repeated: false
  allowedValues: [] # Optional. Specifies allowed values for the input. Use a comma-separated list for multiple values.
  defaultValue: # optional. You can specify the default value (either a string or a number) at this point, for now, it supports a single value.
  showField: true  # boolean: true | false
  required: true
- name: HarFile # A unique identifier of the task input
  description: HarFile # A concise description of the task input
  dataType: FILE
  repeated: false
  allowedValues: [] # Optional. Specifies allowed values for the input. Use a comma-separated list for multiple values.
  defaultValue: # optional. You can specify the default value (either a string or a number) at this point, for now, it supports a single value.
  showField: true  # boolean: true | false
  required: true
outputs:
- name: HARCookieReport
  description: HARCookieReport
  dataType: FILE
- name: LogFile
  description: LogFile
  dataType: FILE
- name: ComplianceStatus_
  description: compliance status of the task
  dataType: STRING
- name: CompliancePCT_
  description: compliance percentage of the task
  dataType: INT
