authors:
- sangavi.l@continube.com
domain: continube
createdDate: 14/12/2023
name: AWSAccessKeyRotationReport
displayName: AWS Access Key Rotation Report
version: '1.0'
description: AWS Access Key Rotation Report
shaToken: ''
showInCatalog: true
icon: fas fa-sort-amount-down-alt
type: go
tags:
- application
applicationType: application
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- name: MaxAccessKeyAge
  description: Maximum Access Key Age
  dataType: INT
  repeated: false
  allowedValues: []
  defaultValue: '90'
  showField: true
  required: true
- name: AWSCredentialReport
  description: AWS Credential Report
  dataType: FILE
  repeated: false
  allowedValues: []
  defaultValue: ''
  showField: true
  required: true
outputs:
- name: AccessKeyRotationReport
  description: Access Key Rotation Report
  dataType: FILE
- name: LogFile
  description: Access Key Rotation Log File
  dataType: FILE
- name: MetaFile
  description: Access Key Rotation Field Meta
  dataType: FILE
- name: CompliancePCT_
  description: Compliance Percentage
  dataType: INT
- name: ComplianceStatus_
  description: Compliance Status
  dataType: STRING
