userObject:
  app:
    name: Kubernetes
    appURL: http://localhost.com
    appPort: "0"
    appTags:
      appType:
      - kubernetes
      environment:
      - logical
      execlevel:
      - app
    userDefinedCredentials:
      Jumphost:
        UserID: "$INSTANCE_USER_NAME"
        LoginUrl: "$INSTANCE_LOGIN_URL"
        SshPrivateKey: "$INSTANCE_SSH_PRIVATE_KEY"
userInputs:
  DataFile: "<<MINIO_FILE_PATH>>"
  LogFile : "<<MINIO_FILE_PATH>>"
fromDate: 2024-11-28T04:46:09Z
toDate: 2024-11-28T04:46:09Z