apiVersion: v1alpha1
kind: rule
meta:
  name: PrivacyBisonCspVulnerabilityCheck
  purpose: Privacy bison CSP vulnerabilityCheck
  description: To ensure that the Content Security Policy (CSP) implemented on a website or web application is configured correctly and adheres to best practices.
  labels:
    appType:
    - privacybisonconnector
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - privacybisonconnector
spec:
  inputs:
    HarFile: <<MINIO_FILE_PATH>>
  inputsMeta__:
  - name: HarFile
    dataType: FILE
    format: json
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: PrivacyBisonCspVulnerabilityCheck
    alias: t1
    type: task
    appTags:
      appType:
      - privacybisonconnector
      environment:
      - logical
      execlevel:
      - app
    purpose: Privacy bison CSP vulnerabilityCheck
    description: To ensure that the Content Security Policy (CSP) implemented on a website or web application is configured correctly and adheres to best practices.
  ioMap:
  - 't1.Input.HarFile:=*.Input.HarFile'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.CSPVulnerabilityReport:=t1.Output.CSPVulnerabilityReport'
  - '*.Output.LogFile:=t1.Output.LogFile'
