authors:
- musadhiek.p@continube.com
domain: continube
createdDate: 24/01/2024
name: GetAzureServiceBusData
displayName: Get Azure ServiceBus Data
version: '1.0'
description: Get Azure ServiceBus Data
shaToken: ''
showInCatalog: true
icon: fa-solid fa-database
type: python
tags:
- generic
applicationType: generic
userObjectJSONInBase64: ''
systemObjectJSONInBase64: ''
inputs:
- {}
outputs:
- name: AzureServiceBusNameSpaces
  description: AzureServiceBusNameSpaces
  dataType: FILE
- name: ServiceBusNameSpacesDiagnosticSettings
  description: ServiceBusNameSpacesDiagnosticSettings
  dataType: FILE
- name: LogFile
  description: LogFile
  dataType: FILE
- name: ComplianceStatus_
  description: ComplianceStatus_
  dataType: STRING
- name: CompliancePCT_
  description: CompliancePCT_
  dataType: INT
