apiVersion: v1alpha1
kind: rule
meta:
  name: GetFilterAWSConfigRuleEvaualtionDetails
  purpose: Get aws rule config details based on the config rule
  description: Get aws rule config details based on the config rule
  labels:
    appType:
    - aws
    environment:
    - logical
    execlevel:
    - app
  annotations:
    annotateType:
    - aws
spec:
  inputs:
    AWSConfigRule: 
    AWSConfigRulesFile: <<MINIO_FILE_PATH>>
    AWSConfigRuleEvaluationStatusFile: <<MINIO_FILE_PATH>>
    RuleConfigFile: <<MINIO_FILE_PATH>>
    Account: 
  inputsMeta__:
  - name: AWSConfigRule
    dataType: STRING
    repeated: false
    defaultValue: ''
    allowedValues: []
    showField: true
    required: true
  - name: AWSConfigRulesFile
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: AWSConfigRuleEvaluationStatusFile
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  - name: RuleConfigFile
    dataType: FILE
    repeated: false
    defaultValue: <<MINIO_FILE_PATH>>
    allowedValues: []
    showField: true
    required: true
  tasks:
  - name: GetFilterAWSConfigRuleEvaualtionDetails
    alias: t1
    type: task
    appTags:
      appType:
      - aws
      environment:
      - logical
      execlevel:
      - app
    purpose: Get AWS rule config details based on the config rule
    description: Get AWS rule config details based on the config rule
  ioMap:
  - 't1.Input.AWSConfigRule:=*.Input.AWSConfigRule'
  - 't1.Input.AWSConfigRulesFile:=*.Input.AWSConfigRulesFile'
  - 't1.Input.AWSConfigRuleEvaluationStatusFile:=*.Input.AWSConfigRuleEvaluationStatusFile'
  - 't1.Input.RuleConfigFile:=*.Input.RuleConfigFile'
  - '*.Output.CompliancePCT_:=t1.Output.CompliancePCT_'
  - '*.Output.ComplianceStatus_:=t1.Output.ComplianceStatus_'
  - '*.Output.AwsConfigRuleFile:=t1.Output.AwsConfigRuleFile'
  - '*.Output.LogFile:=t1.Output.LogFile' 
